version: '3'
services:
    nuxt:
        restart: unless-stopped
        build:
            context: .
        networks:
            - web
        env_file:
            - .env
        ports:
            - '3000:3000'
        logging:
            driver: 'json-file'
            options:
                max-size: '50m'
networks:
    web:
        external: true
